import { join } from "node:path";

import { ensureDir, fileExists, writeTextFile } from "../../../shared/fs";
import type { GeneratorResult, InitContext } from "../types";

// Component bodies live under orycms/; the App Router files are thin re-export
// shims so all CMS source stays inside the dedicated /orycms folder.

// ── Component bodies (written to orycms/) ──────────────────────────────────────

const ADMIN_COMPONENT = `// OryCMS Admin — generated by \`orycms init\`
// Replace this with your admin UI component or use the built-in OryCMS admin.
export default function AdminPage() {
  return (
    <main>
      <h1>OryCMS Admin</h1>
      <p>Configure your admin panel in orycms.config.ts.</p>
    </main>
  );
}
`;

const COLLECTIONS_COMPONENT = `// OryCMS Admin — generated by \`orycms init\`
export default function CollectionsPage() {
  return (
    <main>
      <h1>Collections</h1>
      <p>Define your content collections in orycms.config.ts.</p>
    </main>
  );
}
`;

const PLUGINS_COMPONENT = `// OryCMS Admin — generated by \`orycms init\`
export default function PluginsPage() {
  return (
    <main>
      <h1>Plugins</h1>
      <p>Manage your OryCMS plugins here.</p>
    </main>
  );
}
`;

// ── Shim builder ───────────────────────────────────────────────────────────────

/** A one-level `app/<seg>/page.tsx` re-exports `../../orycms/<target>`. */
function shim(target: string): string {
  return `// OryCMS Admin — generated by \`orycms init\`\nexport { default } from "../../orycms/${target}";\n`;
}

// ── Helpers ────────────────────────────────────────────────────────────────────

function writeFileIfAbsent(cwd: string, relPath: string, content: string): GeneratorResult {
  const full = join(cwd, relPath);
  if (fileExists(full)) {
    return { path: relPath, status: "skipped", description: `${relPath} already exists` };
  }
  ensureDir(join(full, ".."));
  writeTextFile(full, content);
  return { path: relPath, status: "created" };
}

/** Write the orycms component body and its thin app-route shim. */
function writeRoute(
  cwd: string,
  orycmsRel: string,
  body: string,
  appRel: string,
): GeneratorResult[] {
  const target = orycmsRel.replace(/^orycms\//, "").replace(/\.tsx$/, "");
  return [
    writeFileIfAbsent(cwd, orycmsRel, body),
    writeFileIfAbsent(cwd, appRel, shim(target)),
  ];
}

// ── Idempotent runner ─────────────────────────────────────────────────────────

/**
 * Generate the OryCMS admin routes as thin App Router shims that re-export
 * component bodies stored under orycms/admin/. Each file is only written when
 * it does not already exist.
 */
export function generateAppRoutes(ctx: InitContext): GeneratorResult[] {
  return [
    ...writeRoute(ctx.cwd, "orycms/admin/admin-page.tsx", ADMIN_COMPONENT, "app/admin/page.tsx"),
    ...writeRoute(
      ctx.cwd,
      "orycms/admin/collections-page.tsx",
      COLLECTIONS_COMPONENT,
      "app/collections/page.tsx",
    ),
    ...writeRoute(
      ctx.cwd,
      "orycms/admin/plugins-page.tsx",
      PLUGINS_COMPONENT,
      "app/plugins/page.tsx",
    ),
  ];
}
