import { join } from "node:path";

import { ensureDir, fileExists, writeTextFile } from "../../../shared/fs";
import type { GeneratorResult, InitContext } from "../types";

// ── Content builders ──────────────────────────────────────────────────────────

const ADMIN_PAGE = `// OryCMS Admin — generated by \`orycms init\`
// Replace this with your admin UI component or use the built-in OryCMS admin.
export default function AdminPage() {
  return (
    <main>
      <h1>OryCMS Admin</h1>
      <p>Configure your admin panel in orycms.config.ts.</p>
    </main>
  );
}
`;

const COLLECTIONS_PAGE = `// OryCMS Collections — generated by \`orycms init\`
export default function CollectionsPage() {
  return (
    <main>
      <h1>Collections</h1>
      <p>Define your content collections in orycms.config.ts.</p>
    </main>
  );
}
`;

const PLUGINS_PAGE = `// OryCMS Plugins — generated by \`orycms init\`
export default function PluginsPage() {
  return (
    <main>
      <h1>Plugins</h1>
      <p>Manage your OryCMS plugins here.</p>
    </main>
  );
}
`;

// ── Helpers ───────────────────────────────────────────────────────────────────

function writeRoute(cwd: string, relPath: string, content: string): GeneratorResult {
  const full = join(cwd, relPath);
  if (fileExists(full)) {
    return { path: relPath, status: "skipped", description: `${relPath} already exists` };
  }
  ensureDir(join(cwd, relPath, ".."));
  writeTextFile(full, content);
  return { path: relPath, status: "created" };
}

// ── Idempotent runner ─────────────────────────────────────────────────────────

/**
 * Generate the three OryCMS App Router route files.
 * Each file is only written when it does not already exist.
 */
export function generateAppRoutes(ctx: InitContext): GeneratorResult[] {
  return [
    writeRoute(ctx.cwd, "app/admin/page.tsx", ADMIN_PAGE),
    writeRoute(ctx.cwd, "app/collections/page.tsx", COLLECTIONS_PAGE),
    writeRoute(ctx.cwd, "app/plugins/page.tsx", PLUGINS_PAGE),
  ];
}
