import { join } from "node:path";

import { fileExists, readTextFile, writeTextFile } from "../../../shared/fs";
import type { AuthProvider, DatabaseProvider, GeneratorResult, InitContext } from "../types";

// ── Env var lookup tables ─────────────────────────────────────────────────────

const DB_VARS: Record<DatabaseProvider, string[]> = {
  postgresql: ["DATABASE_URL=postgresql://user:password@localhost:5432/mydb"],
  mysql: ["DATABASE_URL=mysql://user:password@localhost:3306/mydb"],
  mariadb: ["DATABASE_URL=mysql://user:password@localhost:3306/mydb"],
  sqlite: ["DATABASE_URL=file:./mydb.sqlite"],
  mongodb: ["MONGODB_URI=mongodb://localhost:27017/mydb"],
  supabase: [
    "SUPABASE_URL=https://your-project.supabase.co",
    "SUPABASE_ANON_KEY=your-anon-key",
    "SUPABASE_SERVICE_KEY=your-service-key",
  ],
  neon: [
    "DATABASE_URL=postgresql://user:password@ep-xxx.us-east-2.aws.neon.tech/mydb?sslmode=require",
  ],
  firebase: [
    "FIREBASE_PROJECT_ID=your-project-id",
    "FIREBASE_PRIVATE_KEY=your-private-key",
    "FIREBASE_CLIENT_EMAIL=service@your-project.iam.gserviceaccount.com",
  ],
};

const AUTH_VARS: Record<AuthProvider, string[]> = {
  "better-auth": [
    "BETTER_AUTH_SECRET=your-secret-key-min-32-chars",
    "BETTER_AUTH_URL=http://localhost:3000",
  ],
  "auth-js": ["AUTH_SECRET=your-secret-key-min-32-chars", "AUTH_URL=http://localhost:3000"],
  clerk: [
    "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_test_...",
    "CLERK_SECRET_KEY=sk_test_...",
    "NEXT_PUBLIC_CLERK_SIGN_IN_URL=/sign-in",
    "NEXT_PUBLIC_CLERK_SIGN_UP_URL=/sign-up",
  ],
  none: [],
};

const ORYCMS_SENTINEL = "# OryCMS";

// ── Content builder ───────────────────────────────────────────────────────────

export function buildEnvExample(ctx: InitContext): string {
  const { answers } = ctx;
  const lines: string[] = [`# OryCMS environment variables — generated by \`orycms init\``];

  lines.push("", `# Database (${answers.database})`, ...DB_VARS[answers.database]);

  const authVars = AUTH_VARS[answers.auth];
  if (authVars.length > 0) {
    lines.push("", `# Auth (${answers.auth})`, ...authVars);
  }

  lines.push("", "# OryCMS", "ORYCMS_DATABASE_URL=${DATABASE_URL}");

  return lines.join("\n") + "\n";
}

/**
 * Merge new env vars into an existing .env.example without overwriting lines
 * that are already present (idempotent).
 */
export function mergeEnvExample(existing: string, addition: string): string {
  const existingLines = new Set(existing.split("\n").map((l) => l.trim()));
  const newLines: string[] = [];

  for (const line of addition.split("\n")) {
    if (!existingLines.has(line.trim())) {
      newLines.push(line);
    }
  }

  if (newLines.every((l) => l.trim() === "" || l.startsWith("#"))) {
    return existing; // nothing meaningful to add
  }

  return existing.trimEnd() + "\n\n" + newLines.join("\n") + "\n";
}

// ── Idempotent runner ─────────────────────────────────────────────────────────

export function generateEnvExample(ctx: InitContext): GeneratorResult {
  const path = ".env.example";
  const full = join(ctx.cwd, path);
  const content = buildEnvExample(ctx);

  if (!fileExists(full)) {
    writeTextFile(full, content);
    return { path, status: "created" };
  }

  const existing = readTextFile(full);
  if (existing.includes(ORYCMS_SENTINEL)) {
    return { path, status: "skipped", description: ".env.example already contains OryCMS vars" };
  }

  writeTextFile(full, mergeEnvExample(existing, content));
  return { path, status: "updated" };
}
