import { join } from "node:path";

import { ensureDir, fileExists, readTextFile, writeTextFile } from "../../shared/fs";
import type { GeneratorResult } from "./types";

// ── Types ──────────────────────────────────────────────────────────────────────

export type RouterType = "app" | "pages";

export interface AppStructure {
  /** Which Next.js router was detected. */
  router: RouterType;
  hasAppDir: boolean;
  hasPagesDir: boolean;
  /** True when the admin sub-directory already exists. */
  hasAdminDir: boolean;
  /** Relative path to the admin directory, e.g. "app/admin". */
  adminDirPath: string;
}

/**
 * Called when a file already exists but lacks the OryCMS Admin marker.
 * Return `true` to overwrite, `false` to preserve the existing file.
 */
export type ConfirmFn = (path: string, reason: string) => Promise<boolean>;

export interface BootstrapOptions {
  cwd: string;
  /** Sub-path for the admin route. Default: "admin". */
  adminBasePath?: string;
  /** Invoked before overwriting a pre-existing user file. */
  confirm?: ConfirmFn;
  /**
   * Override the auto-detected router type.
   * Useful when the caller knows the intended router but the filesystem
   * already has the other router's directories (e.g. after runInit creates app/).
   */
  router?: RouterType;
}

export interface BootstrapResult {
  structure: AppStructure;
  files: GeneratorResult[];
}

// ── Sentinel ───────────────────────────────────────────────────────────────────

// Matches files written by both `orycms init` and `orycms bootstrap`.
const SENTINEL = "// OryCMS Admin";

// ── File templates ─────────────────────────────────────────────────────────────

const APP_LAYOUT = `\
// OryCMS Admin — generated by \`orycms bootstrap\`
// Customize this layout to add nav, auth guards, or theme providers.
import type { Metadata } from "next";
import { AdminProvider } from "./provider";

export const metadata: Metadata = {
  title: "OryCMS Admin",
  robots: { index: false, follow: false },
};

export default function AdminLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <AdminProvider>{children}</AdminProvider>;
}
`;

const APP_PAGE = `\
// OryCMS Admin — generated by \`orycms bootstrap\`
export default function AdminPage() {
  return (
    <main>
      <h1>OryCMS Admin</h1>
      <p>Your OryCMS admin panel. Configure it in orycms.config.ts.</p>
    </main>
  );
}
`;

const APP_PROVIDER = `\
// OryCMS Admin — generated by \`orycms bootstrap\`
// Add auth context, theme providers, or other client-side wrappers here.
"use client";

export function AdminProvider({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}
`;

const PAGES_INDEX = `\
// OryCMS Admin — generated by \`orycms bootstrap\`
export default function AdminPage() {
  return (
    <main>
      <h1>OryCMS Admin</h1>
      <p>Your OryCMS admin panel. Configure it in orycms.config.ts.</p>
    </main>
  );
}
`;

// ── Private helpers ────────────────────────────────────────────────────────────

async function writeWithConfirm(
  cwd: string,
  relPath: string,
  content: string,
  confirm?: ConfirmFn,
): Promise<GeneratorResult> {
  const full = join(cwd, relPath);

  if (!fileExists(full)) {
    ensureDir(join(full, ".."));
    writeTextFile(full, content);
    return { path: relPath, status: "created" };
  }

  const existing = readTextFile(full);
  if (existing.includes(SENTINEL)) {
    return { path: relPath, status: "skipped", description: "already bootstrapped" };
  }

  // Pre-existing user file — ask before touching it
  const overwrite = confirm
    ? await confirm(relPath, "file exists without OryCMS Admin marker")
    : false;

  if (!overwrite) {
    return { path: relPath, status: "skipped", description: "preserved existing file" };
  }

  writeTextFile(full, content);
  return { path: relPath, status: "updated" };
}

// ── Public API ─────────────────────────────────────────────────────────────────

/**
 * Detect the Next.js router in use and whether an admin directory is present.
 * Pure — no filesystem mutations.
 */
export function detectAppStructure(cwd: string, adminBasePath = "admin"): AppStructure {
  const hasAppDir = fileExists(join(cwd, "app"));
  const hasPagesDir = fileExists(join(cwd, "pages"));

  // App Router has priority; fall back to Pages Router; default to App Router
  const router: RouterType = hasAppDir || !hasPagesDir ? "app" : "pages";

  const adminDirPath =
    router === "app" ? `app/${adminBasePath}` : `pages/${adminBasePath}`;
  const hasAdminDir = fileExists(join(cwd, adminDirPath));

  return { router, hasAppDir, hasPagesDir, hasAdminDir, adminDirPath };
}

/**
 * Install OryCMS Admin scaffold files into an existing Next.js project.
 *
 * Behaviour:
 * - Detects App Router vs Pages Router automatically.
 * - Creates the admin directory and its files if they are absent.
 * - Skips any file that already contains the OryCMS Admin marker (idempotent).
 * - Calls `confirm` before overwriting user-owned files that lack the marker.
 * - Never touches files outside the admin directory.
 *
 * App Router generates: layout.tsx, page.tsx, provider.tsx
 * Pages Router generates: index.tsx
 */
export async function bootstrapAdmin(options: BootstrapOptions): Promise<BootstrapResult> {
  const { cwd, adminBasePath = "admin", confirm } = options;
  const detected = detectAppStructure(cwd, adminBasePath);
  // Caller may override the router when filesystem state doesn't reflect the intent
  // (e.g. runInit has already created app/ even though the user wants Pages Router).
  const structure: AppStructure = options.router
    ? { ...detected, router: options.router, adminDirPath: options.router === "app" ? `app/${adminBasePath}` : `pages/${adminBasePath}` }
    : detected;
  const files: GeneratorResult[] = [];

  if (structure.router === "app") {
    const dir = `app/${adminBasePath}`;
    files.push(await writeWithConfirm(cwd, `${dir}/layout.tsx`, APP_LAYOUT, confirm));
    files.push(await writeWithConfirm(cwd, `${dir}/page.tsx`, APP_PAGE, confirm));
    files.push(await writeWithConfirm(cwd, `${dir}/provider.tsx`, APP_PROVIDER, confirm));
  } else {
    const dir = `pages/${adminBasePath}`;
    files.push(await writeWithConfirm(cwd, `${dir}/index.tsx`, PAGES_INDEX, confirm));
  }

  return { structure, files };
}
